model_reasoning_effort = "high"
model_verbosity = "high"
# show_raw_agent_reasoning = true
approval_policy = "on-request"
sandbox_mode = "workspace-write"
project_doc_max_bytes = 65536
project_doc_fallback_filenames = ["CLAUDE.md", "AmazonQ.md"]
# network_access = true

# By default, only the cwd for the Codex session will be writable (and $TMPDIR on macOS),
# but you can specify additional writable folders in this array.
writable_roots = ["/tmp"]

# # Replace builtâ€‘in instructions
# # `USER` must be manually replaced with the actual username
# experimental_instructions_file = "/home/USER/.codex/base_instruction.override.md"
# experimental_compact_prompt_file = "/home/USER/.codex/compact_instruction.override.md"

[features]
# unified_exec = true
# experimental_sandbox_command_assessment = true
apply_patch_freeform = true
streamable_shell = true     # enable the streamable exec tool
web_search_request = true   # allow the model to request web searches
# view_image_tool defaults to true; omit to keep defaults

[sandbox_workspace_write]
network_access = true

[tui]
# Send desktop notifications when approvals are required or a turn completes.
# Defaults to false.
notifications = true

[notice]
hide_full_access_warning = true

# [mcp_servers.langchain-docs]
# url = "https://docs.langchain.com/mcp"
# MCP Servers
[mcp_servers.context7]
command = "cmd"
args = ["-c", "npx @upstash/context7-mcp@latest"]

[mcp_servers."mcp-deepwiki"]
command = "cmd"
args = ["-c", "npx -y mcp-deepwiki@latest"]

[mcp_servers.time]
command = "uvx"
args = ["mcp-server-time"]

[mcp_servers."sequentialthinking-tools"]
command = "cmd"
args = ["-c", "npx mcp-sequentialthinking-tools"]

[mcp_servers."actor-critic-thinking"]
command = "cmd"
args = ["-c", "npx -y mcp-server-actor-critic-thinking"]

[mcp_servers."shannon-thinking"]
command = "cmd"
args = ["-c", "npx -y server-shannon-thinking@latest"]

[mcp_servers.ast-grep]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/ast-grep/ast-grep-mcp",
    "ast-grep-server",
]

[mcp_servers.ripgrep]
command = "cmd"
args = ["-c", "npx -y mcp-ripgrep@latest"]

[mcp_servers.repomix]
command = "cmd"
args = ["-c", "npx -y repomix --mcp"]
