model_reasoning_effort = "high"
model_verbosity = "high"
# show_raw_agent_reasoning = true
approval_policy = "on-request"
sandbox_mode = "workspace-write"
project_doc_max_bytes = 65536
project_doc_fallback_filenames = ["CLAUDE.md", "README.md"]
# network_access = true

# By default, only the cwd for the Codex session will be writable (and $TMPDIR on macOS),
# but you can specify additional writable folders in this array.
writable_roots = ["/tmp"]

# # Replace builtâ€‘in instructions
# # `USER` must be manually replaced with the actual username
# experimental_instructions_file = "/home/USER/.codex/base_instruction.override.md"
# experimental_compact_prompt_file = "/home/USER/.codex/compact_instruction.override.md"

[features]
apply_patch_freeform = true
streamable_shell = true     # enable the streamable exec tool
web_search_request = true   # allow the model to request web searches
# view_image_tool defaults to true; omit to keep defaults
skills = true
tui2 = true

[sandbox_workspace_write]
network_access = true

[tui]
# Send desktop notifications when approvals are required or a turn completes.
# Defaults to false.
notifications = true

[notice]
hide_full_access_warning = true

# [mcp_servers.langchain-docs]
# url = "https://docs.langchain.com/mcp"

[mcp_servers.fetch]
command = "uvx"
args = ["mcp-server-fetch"]

[mcp_servers.actor-critic-thinking]
command = "npx"
args = ["-y", "mcp-server-actor-critic-thinking"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.docfork]
command = "npx"
args = ["-y", "docfork"]

[mcp_servers.ast-grep]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/ast-grep/ast-grep-mcp",
    "ast-grep-server",
]

[mcp_servers.ripgrep]
command = "npx"
args = ["-y", "mcp-ripgrep@latest"]

[mcp_servers.sequentialthinking-tools]
command = "npx"
args = ["mcp-sequentialthinking-tools"]

[mcp_servers.shannon-thinking]
command = "npx"
args = ["-y", "server-shannon-thinking@latest"]

[mcp_servers.time]
command = "uvx"
args = ["mcp-server-time"]

[mcp_servers.code-index]
command = "uvx"
args = ["code-index-mcp"]
